package com.verizon.bdcpe.adobelivestream.collector

/*
  * Created by Alvaro Muir<alvaro.muir@verizon.com>
  * Verizon Big Data & Cloud Platform Engineering
  * 7/23/17.
  */

//ToDo: Review for missing properties
object HitModel {
  case class Hit(
    var reportSuite: Option[String] = None,
    var timeGMT: Option[Double] = None,
    var receivedTimeGMT: Option[Double] = None,
    var hitIdHigh: Option[Double] = None,
    var hitIdLow: Option[Double] = None,
    var sessionId: Option[Double] = None,
    var mcVisIdHigh: Option[Double] = None,
    var mcVisIdLow: Option[Double] = None,
    var visIdHigh: Option[Double] = None,
    var visIdLow: Option[Double] = None,
    var visIdType: Option[Double] = None,
    var visitorId: Option[Double] = None,
    var props: Option[Map[Option[String], Any]] = None,
    var evars: Option[Map[Option[String], Map[Option[String], Any]]] = None,
    var events: Option[Map[Option[String], Any]] = None,
    var hierarchies: Option[Map[Option[String], Any]] = None,
    var geoCountry: Option[String] = None,
    var geoRegion: Option[String] = None,
    var geoCity: Option[String] = None,
    var geoZip: Option[String] = None,
    var geoDMA: Option[Double] = None,
    var geoLatitude: Option[Double] = None,
    var geoLongitude: Option[Double] = None,
    var connectionType: Option[String] = None,
    var topLevelDomain: Option[String] = None,
    var languageAbbrev: Option[String] = None,
    var language: Option[String] = None,
    var searchEngine: Option[String] = None,
    var bot: Option[String] = None,
    var operatingSystem: Option[String] = None,
    var browserType: Option[String] = None,
    var browser: Option[String] = None,
    var javascriptVersion: Option[String] = None,
    var monitorWidth: Option[Double] = None,
    var monitorHeight: Option[Double] = None,
    var monitorColorDepth: Option[String] = None,
    var mobileDeviceType: Option[String] = None,
    var mobileDeviceName: Option[String] = None,
    var mobileManufacturer: Option[String] = None,
    var mobileScreenWidth: Option[Double] = None,
    var mobileScreenHeight: Option[Double] = None,
    var mobileCookieSupport: Option[Boolean] = None,
    var mobileColorDepth: Option[String] = None,
    var mobileAudioSupport: Option[String] = None,
    var mobileVideoSupport: Option[String] = None,
    var pageURL: Option[String] = None,
    var pageName: Option[String] = None,
    var usesPersistentCookie: Option[Double] = None,
    var homePage: Option[Double] = None,
    var browserHeight: Option[Double] = None,
    var browserWidth: Option[Double] = None,
    var javaEnabled: Option[Boolean] = None,
    var ip: Option[String] = None,
    var isErrorPage: Option[Boolean] = None,
    var purchaseId: Option[String] = None,
    var referrer: Option[String] = None,
    var state: Option[String] = None,
    var userAgent: Option[String] = None,
    var plugins: Option[String] = None,
    var currency: Option[String] = None,
    var hitSource: Option[Double] = None,
    var transactionId: Option[String] = None,
    var truncated: Option[Boolean] = None,
    var zip: Option[String] = None
 )
}